/**
 * City → state lookup. Used by:
 *   - LocationPicker (auto-infer state when the user picks one of their
 *     assigned cities so the lead row has both fields populated)
 *   - LeadsGeoMap (bucket leads by state at low zooms even when the row
 *     has no state column)
 *
 * Keep this catalog in sync with the larger CITY_TABLE in
 * `components/crm/charts/LeadsGeoMap.tsx`. Two callers, one source of
 * truth; if a city is missing from the map it falls back to the
 * existing free-text behaviour rather than blowing up.
 *
 * Names are exact-match case-sensitive — match the values seeded into
 * `cities` + `crm_cities` so admins picking from the existing list
 * always resolve. Add a city here when it goes into the DB seed.
 */
export const CITY_TO_STATE: Record<string, string> = {
  // Metros + state capitals
  'Ahmedabad': 'Gujarat',
  'Bengaluru': 'Karnataka',
  'Bhopal': 'Madhya Pradesh',
  'Bhubaneswar': 'Odisha',
  'Chandigarh': 'Chandigarh',
  'Chennai': 'Tamil Nadu',
  'Coimbatore': 'Tamil Nadu',
  'Delhi': 'Delhi',
  'New Delhi': 'Delhi',
  'Gurugram': 'Haryana',
  'Gurgaon': 'Haryana',
  'Guwahati': 'Assam',
  'Hyderabad': 'Telangana',
  'Indore': 'Madhya Pradesh',
  'Jaipur': 'Rajasthan',
  'Kanpur': 'Uttar Pradesh',
  'Kolkata': 'West Bengal',
  'Kochi': 'Kerala',
  'Lucknow': 'Uttar Pradesh',
  'Ludhiana': 'Punjab',
  'Mumbai': 'Maharashtra',
  'Mysuru': 'Karnataka',
  'Nagpur': 'Maharashtra',
  'Noida': 'Uttar Pradesh',
  'Panaji': 'Goa',
  'Patna': 'Bihar',
  'Pune': 'Maharashtra',
  'Raipur': 'Chhattisgarh',
  'Ranchi': 'Jharkhand',
  'Surat': 'Gujarat',
  'Thiruvananthapuram': 'Kerala',
  'Trivandrum': 'Kerala',
  'Vadodara': 'Gujarat',
  'Varanasi': 'Uttar Pradesh',
  'Visakhapatnam': 'Andhra Pradesh',
  'Vizag': 'Andhra Pradesh',
  // Jharkhand district HQs (Tata Tiscon's beat)
  'Bokaro': 'Jharkhand',
  'Bokaro Steel City': 'Jharkhand',
  'Deoghar': 'Jharkhand',
  'Dhanbad': 'Jharkhand',
  'Dumka': 'Jharkhand',
  'Giridih': 'Jharkhand',
  'Godda': 'Jharkhand',
  'Hazaribagh': 'Jharkhand',
  'Jamshedpur': 'Jharkhand',
  'Jamtara': 'Jharkhand',
  'Pakur': 'Jharkhand',
  'Sahibganj': 'Jharkhand',
  // Misc commercial centres
  'Faridabad': 'Haryana',
  'Ghaziabad': 'Uttar Pradesh',
  'Greater Noida': 'Uttar Pradesh',
  'Agra': 'Uttar Pradesh',
  'Allahabad': 'Uttar Pradesh',
  'Prayagraj': 'Uttar Pradesh',
  'Meerut': 'Uttar Pradesh',
  'Aligarh': 'Uttar Pradesh',
  'Bareilly': 'Uttar Pradesh',
  'Gorakhpur': 'Uttar Pradesh',
  'Jodhpur': 'Rajasthan',
  'Udaipur': 'Rajasthan',
  'Ajmer': 'Rajasthan',
  'Kota': 'Rajasthan',
  'Bikaner': 'Rajasthan',
  'Amritsar': 'Punjab',
  'Jalandhar': 'Punjab',
  'Mohali': 'Punjab',
  'Patiala': 'Punjab',
  'Karnal': 'Haryana',
  'Panipat': 'Haryana',
  'Hisar': 'Haryana',
  'Ambala': 'Haryana',
  'Sonipat': 'Haryana',
  'Rohtak': 'Haryana',
  'Thane': 'Maharashtra',
  'Navi Mumbai': 'Maharashtra',
  'Nashik': 'Maharashtra',
  'Aurangabad': 'Maharashtra',
  'Solapur': 'Maharashtra',
  'Kolhapur': 'Maharashtra',
  'Ahmednagar': 'Maharashtra',
  'Mangaluru': 'Karnataka',
  'Mangalore': 'Karnataka',
  'Hubballi': 'Karnataka',
  'Belagavi': 'Karnataka',
  'Madurai': 'Tamil Nadu',
  'Tiruchirappalli': 'Tamil Nadu',
  'Salem': 'Tamil Nadu',
  'Tirunelveli': 'Tamil Nadu',
  'Vellore': 'Tamil Nadu',
  'Erode': 'Tamil Nadu',
  'Tiruppur': 'Tamil Nadu',
  'Vijayawada': 'Andhra Pradesh',
  'Guntur': 'Andhra Pradesh',
  'Tirupati': 'Andhra Pradesh',
  'Warangal': 'Telangana',
  'Bhilai': 'Chhattisgarh',
  'Bilaspur': 'Chhattisgarh',
  'Jabalpur': 'Madhya Pradesh',
  'Gwalior': 'Madhya Pradesh',
  'Ujjain': 'Madhya Pradesh',
  'Ratlam': 'Madhya Pradesh',
  'Cuttack': 'Odisha',
  'Rourkela': 'Odisha',
  'Sambalpur': 'Odisha',
  'Berhampur': 'Odisha',
  'Dehradun': 'Uttarakhand',
  'Haridwar': 'Uttarakhand',
  'Roorkee': 'Uttarakhand',
  'Shimla': 'Himachal Pradesh',
  'Dharamshala': 'Himachal Pradesh',
  'Jammu': 'Jammu and Kashmir',
  'Srinagar': 'Jammu and Kashmir',
  'Leh': 'Ladakh',
  'Imphal': 'Manipur',
  'Shillong': 'Meghalaya',
  'Aizawl': 'Mizoram',
  'Kohima': 'Nagaland',
  'Itanagar': 'Arunachal Pradesh',
  'Agartala': 'Tripura',
  'Gangtok': 'Sikkim',
  'Dibrugarh': 'Assam',
  'Silchar': 'Assam',
  'Siliguri': 'West Bengal',
  'Durgapur': 'West Bengal',
  'Asansol': 'West Bengal',
  'Howrah': 'West Bengal',
  'Bhagalpur': 'Bihar',
  'Gaya': 'Bihar',
  'Muzaffarpur': 'Bihar',
  'Darbhanga': 'Bihar',
  'Puducherry': 'Puducherry',
  'Port Blair': 'Andaman and Nicobar Islands',
};

/** Returns the state for the given city, or undefined if unknown.
 *  Match is exact (case-sensitive) — callers should pass the city
 *  name as it appears in cities/crm_cities. */
export function stateForCity(city?: string | null): string | undefined {
  if (!city) return undefined;
  return CITY_TO_STATE[city];
}
