export const CRM_INDUSTRIES: readonly string[] = [
  'Agriculture',
  'Automotive',
  'Banking & Financial Services',
  'Chemicals',
  'Construction',
  'Consumer Goods',
  'Education',
  'Energy & Utilities',
  'FMCG',
  'Food & Beverage',
  'Government',
  'Healthcare',
  'Hospitality',
  'Information Technology',
  'Insurance',
  'Logistics & Transportation',
  'Manufacturing',
  'Media & Entertainment',
  'Mining & Metals',
  'Non-Profit',
  'Pharmaceuticals',
  'Real Estate',
  'Retail',
  'Steel',
  'Telecommunications',
  'Textiles',
  'Travel & Tourism',
  'Wholesale Distribution',
  'Other',
] as const;
